package xowxstat

// Code generated by xo. DO NOT EDIT.

// UserStat represents a row from 'user_stat_'.
type UserStat struct {
	UserID          int `json:"user_id"`          // user_id
	GroupID         int `json:"group_id"`         // group_id
	WordCount       int `json:"word_count"`       // word_count
	CorrectionCount int `json:"correction_count"` // correction_count
	ShareCount      int `json:"share_count"`      // share_count
	MemeCount       int `json:"meme_count"`       // meme_count
}
